# Website settings
baseurl: "/"
base_url: "https://thekkedam.com"
url: "https://thekkedam.com"
domain: "thekkedam.org"
production: true

# Jekyll build settings
paginate: 6
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed  
highlighter: rouge
timezone: 'Europe/Berlin'

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - rouge
